language: js


before_deploy:
  - ng build
deploy:
  provider: s3
  access_key_id: ""
  secret_access_key: ""
  bucket: "clientbucket123"
  skip_cleanup: true
  region: "US East (N. Virginia)"
  acl: public_read
  local_dir: dist
  on:
      branch: master
 